/*
 * AABB Computer Implementation
 *
 * MatForge - CIS 5650 Fall 2025
 */

#include "aabb_computer.hpp"
#include <nvvk/check_error.hpp>
#include <nvvk/pipeline.hpp>

// Compiled shader (auto-generated by CMake)
#include "_autogen/compute_displacement_aabbs.compute.slang.h"

void AabbComputer::init(VkDevice device, nvvk::ResourceAllocator* allocator)
{
    m_device    = device;
    m_allocator = allocator;

    createDescriptorSetLayout();
    createPipeline();
}

void AabbComputer::deinit()
{
    if(m_device == VK_NULL_HANDLE)
        return;

    vkDestroyPipeline(m_device, m_pipeline, nullptr);
    vkDestroyPipelineLayout(m_device, m_pipelineLayout, nullptr);
    vkDestroyDescriptorSetLayout(m_device, m_descriptorSetLayout, nullptr);
    vkDestroyDescriptorPool(m_device, m_descriptorPool, nullptr);

    m_bindings.clear();

    m_device    = VK_NULL_HANDLE;
    m_allocator = nullptr;
    m_pipeline  = VK_NULL_HANDLE;
    m_pipelineLayout = VK_NULL_HANDLE;
    m_descriptorSetLayout = VK_NULL_HANDLE;
    m_descriptorPool = VK_NULL_HANDLE;
}

void AabbComputer::createDescriptorSetLayout()
{
    // Binding 0: Vertex positions (StructuredBuffer<float3>)
    m_bindings.addBinding(0, VK_DESCRIPTOR_TYPE_STORAGE_BUFFER, 1, VK_SHADER_STAGE_COMPUTE_BIT);

    // Binding 1: Vertex normals (StructuredBuffer<float3>)
    m_bindings.addBinding(1, VK_DESCRIPTOR_TYPE_STORAGE_BUFFER, 1, VK_SHADER_STAGE_COMPUTE_BIT);

    // Binding 2: Triangle indices (StructuredBuffer<uint>)
    m_bindings.addBinding(2, VK_DESCRIPTOR_TYPE_STORAGE_BUFFER, 1, VK_SHADER_STAGE_COMPUTE_BIT);

    // Binding 3: Output AABBs (RWStructuredBuffer<VkAabbPositionsKHR>)
    m_bindings.addBinding(3, VK_DESCRIPTOR_TYPE_STORAGE_BUFFER, 1, VK_SHADER_STAGE_COMPUTE_BIT);

    NVVK_CHECK(m_bindings.createDescriptorSetLayout(m_device, 0, &m_descriptorSetLayout));

    // Create descriptor pool
    std::vector<VkDescriptorPoolSize> poolSizes;
    poolSizes.push_back({VK_DESCRIPTOR_TYPE_STORAGE_BUFFER, 100});  // Enough for multiple dispatches

    VkDescriptorPoolCreateInfo poolInfo{VK_STRUCTURE_TYPE_DESCRIPTOR_POOL_CREATE_INFO};
    poolInfo.maxSets       = 100;
    poolInfo.poolSizeCount = static_cast<uint32_t>(poolSizes.size());
    poolInfo.pPoolSizes    = poolSizes.data();

    NVVK_CHECK(vkCreateDescriptorPool(m_device, &poolInfo, nullptr, &m_descriptorPool));
}

void AabbComputer::createPipeline()
{
    // Push constant for parameters
    VkPushConstantRange pushConstantRange{};
    pushConstantRange.stageFlags = VK_SHADER_STAGE_COMPUTE_BIT;
    pushConstantRange.offset     = 0;
    pushConstantRange.size       = sizeof(AabbComputeParams);

    // Pipeline layout
    VkPipelineLayoutCreateInfo layoutInfo{VK_STRUCTURE_TYPE_PIPELINE_LAYOUT_CREATE_INFO};
    layoutInfo.setLayoutCount         = 1;
    layoutInfo.pSetLayouts            = &m_descriptorSetLayout;
    layoutInfo.pushConstantRangeCount = 1;
    layoutInfo.pPushConstantRanges    = &pushConstantRange;

    NVVK_CHECK(vkCreatePipelineLayout(m_device, &layoutInfo, nullptr, &m_pipelineLayout));

    // Compute shader stage
    VkShaderModuleCreateInfo shaderInfo{VK_STRUCTURE_TYPE_SHADER_MODULE_CREATE_INFO};
    shaderInfo.codeSize = compute_displacement_aabbs_compute_slang_sizeInBytes;
    shaderInfo.pCode    = compute_displacement_aabbs_compute_slang;

    VkShaderModule shaderModule;
    NVVK_CHECK(vkCreateShaderModule(m_device, &shaderInfo, nullptr, &shaderModule));

    VkPipelineShaderStageCreateInfo stageInfo{VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO};
    stageInfo.stage  = VK_SHADER_STAGE_COMPUTE_BIT;
    stageInfo.module = shaderModule;
    stageInfo.pName  = "main";

    // Compute pipeline
    VkComputePipelineCreateInfo pipelineInfo{VK_STRUCTURE_TYPE_COMPUTE_PIPELINE_CREATE_INFO};
    pipelineInfo.stage  = stageInfo;
    pipelineInfo.layout = m_pipelineLayout;

    NVVK_CHECK(vkCreateComputePipelines(m_device, VK_NULL_HANDLE, 1, &pipelineInfo, nullptr, &m_pipeline));

    // Cleanup shader module
    vkDestroyShaderModule(m_device, shaderModule, nullptr);
}

void AabbComputer::computeAABBs(VkCommandBuffer         cmd,
                                const nvvk::Buffer&     vertexBuffer,
                                const nvvk::Buffer&     normalBuffer,
                                const nvvk::Buffer&     indexBuffer,
                                const nvvk::Buffer&     aabbBuffer,
                                const AabbComputeParams& params)
{
    // Allocate descriptor set
    VkDescriptorSetAllocateInfo allocInfo{VK_STRUCTURE_TYPE_DESCRIPTOR_SET_ALLOCATE_INFO};
    allocInfo.descriptorPool     = m_descriptorPool;
    allocInfo.descriptorSetCount = 1;
    allocInfo.pSetLayouts        = &m_descriptorSetLayout;

    VkDescriptorSet descriptorSet;
    NVVK_CHECK(vkAllocateDescriptorSets(m_device, &allocInfo, &descriptorSet));

    // Prepare buffer descriptors
    std::array<VkDescriptorBufferInfo, 4> bufferInfos;
    std::array<VkWriteDescriptorSet, 4>   writes;

    // Binding 0: Vertex positions
    bufferInfos[0].buffer = vertexBuffer.buffer;
    bufferInfos[0].offset = 0;
    bufferInfos[0].range  = VK_WHOLE_SIZE;

    writes[0] = {VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET};
    writes[0].dstSet          = descriptorSet;
    writes[0].dstBinding      = 0;
    writes[0].descriptorCount = 1;
    writes[0].descriptorType  = VK_DESCRIPTOR_TYPE_STORAGE_BUFFER;
    writes[0].pBufferInfo     = &bufferInfos[0];

    // Binding 1: Vertex normals
    bufferInfos[1].buffer = normalBuffer.buffer;
    bufferInfos[1].offset = 0;
    bufferInfos[1].range  = VK_WHOLE_SIZE;

    writes[1] = {VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET};
    writes[1].dstSet          = descriptorSet;
    writes[1].dstBinding      = 1;
    writes[1].descriptorCount = 1;
    writes[1].descriptorType  = VK_DESCRIPTOR_TYPE_STORAGE_BUFFER;
    writes[1].pBufferInfo     = &bufferInfos[1];

    // Binding 2: Triangle indices
    bufferInfos[2].buffer = indexBuffer.buffer;
    bufferInfos[2].offset = 0;
    bufferInfos[2].range  = VK_WHOLE_SIZE;

    writes[2] = {VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET};
    writes[2].dstSet          = descriptorSet;
    writes[2].dstBinding      = 2;
    writes[2].descriptorCount = 1;
    writes[2].descriptorType  = VK_DESCRIPTOR_TYPE_STORAGE_BUFFER;
    writes[2].pBufferInfo     = &bufferInfos[2];

    // Binding 3: Output AABBs
    bufferInfos[3].buffer = aabbBuffer.buffer;
    bufferInfos[3].offset = 0;
    bufferInfos[3].range  = VK_WHOLE_SIZE;

    writes[3] = {VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET};
    writes[3].dstSet          = descriptorSet;
    writes[3].dstBinding      = 3;
    writes[3].descriptorCount = 1;
    writes[3].descriptorType  = VK_DESCRIPTOR_TYPE_STORAGE_BUFFER;
    writes[3].pBufferInfo     = &bufferInfos[3];

    // Update descriptor set
    vkUpdateDescriptorSets(m_device, static_cast<uint32_t>(writes.size()), writes.data(), 0, nullptr);

    // Bind pipeline and descriptor set
    vkCmdBindPipeline(cmd, VK_PIPELINE_BIND_POINT_COMPUTE, m_pipeline);
    vkCmdBindDescriptorSets(cmd, VK_PIPELINE_BIND_POINT_COMPUTE, m_pipelineLayout, 0, 1, &descriptorSet, 0, nullptr);

    // Push constants
    vkCmdPushConstants(cmd, m_pipelineLayout, VK_SHADER_STAGE_COMPUTE_BIT, 0, sizeof(AabbComputeParams), &params);

    // Dispatch
    // numthreads(256, 1, 1) in shader, so we need (numTriangles + 255) / 256 groups
    uint32_t numGroups = (params.numTriangles + 255) / 256;
    vkCmdDispatch(cmd, numGroups, 1, 1);

    // Insert barrier to ensure AABBs are written before BLAS build
    VkMemoryBarrier barrier{VK_STRUCTURE_TYPE_MEMORY_BARRIER};
    barrier.srcAccessMask = VK_ACCESS_SHADER_WRITE_BIT;
    barrier.dstAccessMask = VK_ACCESS_ACCELERATION_STRUCTURE_READ_BIT_KHR;

    vkCmdPipelineBarrier(cmd, VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT,
                         VK_PIPELINE_STAGE_ACCELERATION_STRUCTURE_BUILD_BIT_KHR, 0, 1, &barrier, 0, nullptr, 0, nullptr);
}
